---
- name: Monitor zSecure Alerts from Kafka for Password Threshold Exceeded Alert (C2P1111I)
  hosts: all
  sources:
    - name: kafka
      ansible.eda.kafka:
        topic: "{{ kafka_topic }}"
        host: "{{ kafka_host }}"
        port: "{{ kafka_port }}"
        security_protocol: "{{ security_protocol }}"
        ssl_cafile: "{{ cafile }}"

      filters:
        - ibm.ibm_eda_zos.security_alerts:
            event_source: "kafka"

  rules:
    - name: Handle Invalid Password Threshold Exceeded Alert (C2P1111I)
      condition:
        all:
          # Event A: zSecure Alert 1111
          - events.a << (
              event.body.alert_code == "C2P1111I"
            )

          # Event B: RACF ICH408I AFTER alert 1111
          - events.b << (
              event.body.message is search("ICH408I")
              and event.body.message is search("LOGON/JOB INITIATION")
              and events.a.meta.received_at < event.meta.received_at
            )
        timeout: 90 seconds
      action:
        run_job_template:
          name: zSecure - Respond to Password Limit Exceeded
          organization: "Default"
