---
- name: Correct all users access for GETSPENT violation
  hosts: "{{ target_hosts | default('localhost') }}.vmec.svl.ibm.com"
  gather_facts: false
  environment: "{{ system_environment }}"
  tasks:
    - name: Extract the user_id
      ansible.builtin.set_fact:
        user_id: "{{ racf_event.line_content | regex_search('USER\\(([^)]+)\\)', '\\1') | first | trim }}"

    - name: "Get second julian date time to be used with pcon"
      ansible.builtin.command: "date '+%j %T'"
      become: false
      register: post_time
      changed_when: post_time.rc != 0

    - name: Print datetime from event
      ansible.builtin.debug:
        var: post_time

    - name: "Run corrective actions for {{ user_id }}"
      ansible.builtin.raw: |
        tsocmd "PERMIT SUPERUSER.PROCESS.GETPSENT CL(UNIXPRIV) ID({{ user_id }}) ACCESS(READ)";
        tsocmd "SETROPTS RACLIST(UNIXPRIV) REFRESH";
      register: result
      changed_when: result.rc == 0
      become: false

    - name: "Print corrective actions output"
      ansible.builtin.debug:
        var: result

    - name: "Run command ps -ef again to trigger RACF violation as {{ user_id }}"
      ansible.builtin.raw: "ps -ef"
      become: true
      register: result
      changed_when: result.rc != 0

    - name: "Retrieve the console log for the second time of {{ post_time.stdout }}"
      ansible.builtin.shell: 'pcon -s 25{{ post_time.stdout }} | grep -i "INSUFFICIENT AUTHORITY TO GETPSENT"'
      become: false
      register: result
      changed_when: result.rc != 0
      ignore_errors: true

    - name: Print console logs
      ansible.builtin.debug:
        var: result

    - name: Assert
      ansible.builtin.assert:
        that:
          - "'INSUFFICIENT AUTHORITY TO GETPSENT' not in result.stdout"
        fail_msg: "GETSPENT FOUND - corrective action was not applied"
        success_msg: "No GETSPENT found - corrective action applied."
