---
- name: Trigger RACF GETSPENT violation
  hosts: "{{ target_hosts | default('localhost') }}.vmec.svl.ibm.com"
  gather_facts: false
  environment: "{{ system_environment }}"
  tasks:
    # -----------------------------------------------------------------------
    # You should run the RACF commands as UID0 or a user with SPECIAL, on ECs,
    # that is user 'OMVSADM'. If you try to use the zos_tso_command module
    # you will trigger some RACF GETPSENT violations because the module will
    # depend on Python, and Python has this GETSPENT issue that happens anytime
    # the process for Python is initialized. Using raw is shell driven, no
    # Python is present thus no RACF violation.
    # Note that because this may be run more than once, I force the clean up
    # {{ user_id }} with the added:
    # tsocmd "SETROPTS LOGOPTIONS(ALWAYS(PROCACT))";tsocmd "PERMIT SUPERUSER.PROCESS.GETPSENT CL(UNIXPRIV) ID({{ user_id }}) ACCESS(NONE)
    # -----------------------------------------------------------------------
    - name: "Run command ps -ef to trigger RACF violation"
      ansible.builtin.raw: |
        tsocmd "RDEFINE UNIXPRIV SUPERUSER.PROCESS.GETPSENT UACC(NONE)";
        tsocmd "SETROPTS LOGOPTIONS(ALWAYS(PROCACT))";
        tsocmd "PERMIT SUPERUSER.PROCESS.GETPSENT CL(UNIXPRIV) ID({{ user_id }}) ACCESS(NONE)";
        tsocmd "SETROPTS RACLIST(UNIXPRIV) REFRESH";
      register: result
      changed_when: result.rc == 0
      become: false

    - name: Print racf permissions result
      ansible.builtin.debug:
        var: result
    # -----------------------------------------------------------------------
    # Get the time before we run any commands we can use it for `pcon`
    # -----------------------------------------------------------------------
    - name: "Get current julian date to be used with pcon"
      ansible.builtin.command: "date '+%j %T'"
      become: false
      register: curr_time
      changed_when: curr_time.rc != 0

    - name: Print current time
      ansible.builtin.debug:
        var: curr_time.stdout

    # -----------------------------------------------------------------------
    # This is not necessary but a sanity check.
    # -----------------------------------------------------------------------
    - name: "Lets be sure whoami works using privilege escalation with {{ user_id }}"
      ansible.builtin.raw: "whoami"
      become: true
      register: result
      changed_when: result.rc != 0

    - name: Print whoami result
      ansible.builtin.debug:
        var: result

    # -----------------------------------------------------------------------
    # Use the ansible.builtin.raw module to execute the `ps -ef` command
    # to trigger the violation using user {{ user_id }} (escalate to this user)
    # -----------------------------------------------------------------------
    - name: "Run command ps -ef again to validate corrective action"
      ansible.builtin.raw: "ps -ef"
      register: ps_output
      changed_when: ps_output.rc != 0
      become: true
