---
- name: Unquarantine a tso user
  hosts: "{{ target_hosts | default('localhost') }}"
  gather_facts: false
  environment: "{{ system_environment }}"

  vars:
    tso_user: "{{ ansible_eda.event.body.target_user | default('UNKNOWN') }}"

  tasks:
    - name: Action when tso_user is UNKNOWN
      when: tso_user == "UNKNOWN"
      block:
        - name: Display message when tso_user is UNKNOWN
          ansible.builtin.debug:
            msg: "Cannot proceed: tso_user was 'UNKNOWN'."

        - name: Set command message for email notice
          ansible.builtin.set_stats:
            data:
              set_command_message: "cannot proceed: tso_user was 'UNKNOWN'"
            per_host: false

    - name: Action to process quarantine for valid tso_user
      when: tso_user != "UNKNOWN"
      block:
        # Submit command to unquarantine the user
        - name: Issue RACF command to unquarantine the user
          ibm.ibm_zos_core.zos_tso_command:
            commands:
              - ALTUSER {{ tso_user }} NOCONTAIN RESUME
            max_rc: 0
          register: altuser_result
          ignore_errors: true

        # Submit command to display the user's attributes
        - name: Issue RACF command to list the user's attributes after unquarantine
          ibm.ibm_zos_core.zos_tso_command:
            commands:
              - LISTUSER {{ tso_user }}
          register: tso_output_after

        - name: Display the user's RACF attributes after unquarantine
          ansible.builtin.debug:
            msg:
              - "After RACF unquarantine command:"
              - "{{ tso_output_after.output[0:4] }}"

        - name: Set command message for email notice
          ansible.builtin.set_stats:
            data:
              set_command_message: "executed the ALTUSER {{ tso_user }} NOCONTAIN RESUME command \
                {{ 'successfully' if altuser_result.output[0].rc <= 0 else 'but failed' }}"
            per_host: false

        # Display the status message for the ALTUSER command
        - name: Display status message for ALTUSER command
          ansible.builtin.debug:
            msg: "ALTUSER {{ tso_user }} NOCONTAIN RESUME command {{ 'was successful' if altuser_result.output[0].rc <= 0 else 'failed' }}"
